apiVersion: v1
kind: Secret
metadata:
  name: ecom-secrets
  namespace: ecom
type: Opaque
stringData:

  # PostgreSQL
  POSTGRES_HOST: "pg-postgresql"
  POSTGRES_PORT: "5432"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "mapa"

  # Per-service connection strings
  USER_DB_CONN: "Host=pg-postgresql;Port=5432;Database=userdb;Username=postgres;Password=mapa"
  PRODUCT_DB_CONN: "Host=pg-postgresql;Port=5432;Database=productdb;Username=postgres;Password=mapa"
  ORDER_DB_CONN: "Host=pg-postgresql;Port=5432;Database=orderdb;Username=postgres;Password=mapa"
  PAYMENT_DB_CONN: "Host=pg-postgresql;Port=5432;Database=paymentdb;Username=postgres;Password=mapa"

  # Redis
  REDIS_CONN: "redis-master:6379"

  # Kafka
  KAFKA_BOOTSTRAP: "kafka.ecom.svc.cluster.local:9092"

  # JWT
  JWT_SIGNING_KEY: "Mapa1234567890SecretKey256Bitlong"
  JWT_ISSUER: "UserService"
  JWT_AUDIENCE: "ecom-users"
  JWT_EXPIRATIONMINUTES: "360" 

  # Stripe
  STRIPE_SECRET_KEY: "sk_test_xxxxx"
  STRIPE_WEBHOOK_SECRET: "whsec_xxxxx"