apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: ecom
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: userservice:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          env:
            - name: ConnectionStrings__DefaultConnection
              valueFrom:
                secretKeyRef:
                  name: ecom-secrets
                  key: USER_DB_CONN
            - name: Jwt__Key
              valueFrom:
                secretKeyRef:
                  name: ecom-secrets
                  key: JWT_SIGNING_KEY
            - name: Jwt__Issuer
              valueFrom:
                secretKeyRef:
                  name: ecom-secrets
                  key: JWT_ISSUER
            - name: Jwt__Audience
              valueFrom:
                secretKeyRef:
                  name: ecom-secrets
                  key: JWT_AUDIENCE
            - name: Jwt__ExpiryMinutes
              valueFrom:
                secretKeyRef:
                  name: ecom-secrets
                  key: JWT_EXPIRATIONMINUTES

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: ecom
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080